stages:
- build
- deploy

build:
  image: docker-inter.kezaihui.com/inf/common/docker:java-latest
  stage: build
  tags:
  - docker-socket
  script:
  - echo "build on $CI_COMMIT_TAG"
  - >
    if [ -z "$CI_COMMIT_TAG" ] ;then
       export CI_COMMIT_TAG=${env}-latest;
       export BUILD_ENV='-P dev';
    else
       export BUILD_ENV='-P prod';
    fi
  - mvn clean install deploy -B -U -e ${BUILD_ENV} -Dmaven.test.skip=true
  - docker pull docker-inter.kezaihui.com/inf/common/java:8
  - docker tag docker-inter.kezaihui.com/inf/common/java:8 java:8
  - mvn docker:build
  - docker tag docker-inter.kezaihui.com/marketing/xxl-job/xxl-job-app:latest docker-inter.kezaihui.com/marketing/xxl-job/xxl-job-app:${CI_COMMIT_TAG}
  - docker push docker-inter.kezaihui.com/marketing/xxl-job/xxl-job-app:${CI_COMMIT_TAG}


deploy:
  image: docker-inter.kezaihui.com/inf/common/kubectl:${env}
  stage: deploy
  tags:
  - DOCKER
  except:
  - master
  script:
  - sh deploy/deploy.sh
  when: manual